mt6895-common: patches: Fix ImsService emergency call crash
Since A16, `includes(String)` in PackagesTagsList has been replaced by
`containsPackage(String)`

ImsLocationHandler still uses `includes(String)`, which causes
NoSuchMethodError error from IMS when attempting to call emergency
services.

Patch ImsLocationHandler to use containsPackage(String) instead.

[archcloudy]: Increase register count in ImsConfigManager also.

(cherry-picked from d0ee2dc3c4e2a0c5284a49b9d30f439f60517ee7)
Different commit message from original author
This is the revised commit message.

Change-Id: I53aeb9c8b6b58404f923d5953c486e2af01ca3b0
Co-authored-by: Angaddeep Singh <angxddeep@gmail.com>
Co-authored-by: codex <codex@users.noreply.github.com>
Signed-off-by: archcloudy <cloudguy9@proton.me>